version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: zugo-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000" # Adjust the port as necessary for your app

volumes:
  my_pgdata:
