openapi: 3.0.0
info:
  title: Plan API
  version: 1.0.0
  description: API for managing plans.
tags:
  - name: Plans
    description: Operations related to plans
paths:
  /plans:
    post:
      tags:
        - Plans
      summary: Create a new plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_name:
                  type: string
                  example: "Retirement Plan"
                plan_description:
                  type: string
                  example: "A plan for retirement savings."
                category:
                  type: string
                  enum: [Discretionary]
                  example: "Discretionary"
                subcategory:
                  type: string
                  enum: [Sapphire]
                  example: "Sapphire"
                risk_profile_id:
                  type: integer
                  example: 1
                model_portfolio_id:
                  type: integer
                  example: 1
                status:
                  type: string
                  enum: [Active, Completed, Dormant]
                  example: "Active"
      responses:
        '201':
          description: Plan created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  plan_name:
                    type: string
                    example: "Retirement Plan"
                  plan_description:
                    type: string
                    example: "A plan for retirement savings."
                  category:
                    type: string
                    example: "Discretionary"
                  subcategory:
                    type: string
                    example: "Sapphire"
                  risk_profile_id:
                    type: integer
                    example: 1
                  model_portfolio_id:
                    type: integer
                    example: 1
                  status:
                    type: string
                    example: "Active"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Plan name is required"

    get:
      tags:
        - Plans
      summary: Retrieve all plans
      responses:
        '200':
          description: A list of plans
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    plan_name:
                      type: string
                      example: "Retirement Plan"
                    plan_description:
                      type: string
                      example: "A plan for retirement savings."
                    category:
                      type: string
                      example: "Discretionary"
                    subcategory:
                      type: string
                      example: "Sapphire"
                    risk_profile_id:
                      type: integer
                      example: 1
                    model_portfolio_id:
                      type: integer
                      example: 1
                    status:
                      type: string
                      example: "Active"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /plans/{id}:
    get:
      tags:
        - Plans
      summary: Retrieve a specific plan by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the plan to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Plan found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  plan_name:
                    type: string
                    example: "Retirement Plan"
                  plan_description:
                    type: string
                    example: "A plan for retirement savings."
                  category:
                    type: string
                    example: "Discretionary"
                  subcategory:
                    type: string
                    example: "Sapphire"
                  risk_profile_id:
                    type: integer
                    example: 1
                  model_portfolio_id:
                    type: integer
                    example: 1
                  status:
                    type: string
                    example: "Active"
        '404':
          description: Plan not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Plan not found"

    put:
      tags:
        - Plans
      summary: Update a plan by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the plan to update
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_name:
                  type: string
                  example: "Retirement Plan"
                plan_description:
                  type: string
                  example: "A plan for retirement savings."
                category:
                  type: string
                  enum: [Discretionary]
                  example: "Discretionary"
                subcategory:
                  type: string
                  enum: [Sapphire]
                  example: "Sapphire"
                risk_profile_id:
                  type: integer
                  example: 1
                model_portfolio_id:
                  type: integer
                  example: 1
                status:
                  type: string
                  enum: [Active, Completed, Dormant]
                  example: "Active"
      responses:
        '200':
          description: Plan updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  plan_name:
                    type: string
                    example: "Retirement Plan"
                  plan_description:
                    type: string
                    example: "A plan for retirement savings."
                  category:
                    type: string
                    example: "Discretionary"
                  subcategory:
                    type: string
                    example: "Sapphire"
                  risk_profile_id:
                    type: integer
                    example: 1
                  model_portfolio_id:
                    type: integer
                    example: 1
                  status:
                    type: string
                    example: "Active"
        '404':
          description: Plan not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Plan not found"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Plan name is required"