openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API for managing products.
tags:
  - name: Products
    description: Operations related to products

paths:
  /products:
    post:
      tags:
        - Products
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                  example: "Investment Fund"
                product_description:
                  type: string
                  example: "A fund for long-term investments."
                category:
                  type: string
                  example: "Equity"
                risk_profile_id:
                  type: integer
                  example: 1
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  product_name:
                    type: string
                    example: "Investment Fund"
                  product_description:
                    type: string
                    example: "A fund for long-term investments."
                  category:
                    type: string
                    example: "Equity"
                  risk_profile_id:
                    type: integer
                    example: 1
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Product name is required"

    get:
      tags:
        - Products
      summary: Retrieve all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    product_name:
                      type: string
                      example: "Investment Fund"
                    product_description:
                      type: string
                      example: "A fund for long-term investments."
                    category:
                      type: string
                      example: "Equity"
                    risk_profile_id:
                      type: integer
                      example: 1
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /products/{id}:
    get:
      tags:
        - Products
      summary: Retrieve a specific product by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  product_name:
                    type: string
                    example: "Investment Fund"
                  product_description:
                    type: string
                    example: "A fund for long-term investments."
                  category:
                    type: string
                    example: "Equity"
                  risk_profile_id:
                    type: integer
                    example: 1
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Product not found"