openapi: 3.0.0
info:
  title: Risk Profile API
  version: 1.0.0
  description: API for managing risk profiles.
tags:
  - name: Risk Profiles
    description: Operations related to risk profiles
paths:
  /risk-profiles:
    post:
      tags:
        - Risk Profiles
      summary: Create a new risk profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                profile_name:
                  type: string
                  example: "Conservative"
                description:
                  type: string
                  example: "A conservative risk profile."
      responses:
        '201':
          description: Risk profile created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  profile_name:
                    type: string
                    example: "Conservative"
                  description:
                    type: string
                    example: "A conservative risk profile."
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Profile name is required"

    get:
      tags:
        - Risk Profiles
      summary: Retrieve all risk profiles
      responses:
        '200':
          description: A list of risk profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    profile_name:
                      type: string
                      example: "Conservative"
                    description:
                      type: string
                      example: "A conservative risk profile."
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /risk-profiles/{id}:
    get:
      tags:
        - Risk Profiles
      summary: Retrieve a specific risk profile by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the risk profile to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Risk profile found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  profile_name:
                    type: string
                    example: "Conservative"
                  description:
                    type: string
                    example: "A conservative risk profile."
        '404':
          description: Risk profile not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "RiskProfile not found"

    put:
      tags:
        - Risk Profiles
      summary: Update a risk profile by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the risk profile to update
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                profile_name:
                  type: string
                  example: "Conservative"
                description:
                  type: string
                  example: "A conservative risk profile."
      responses:
        '200':
          description: Risk profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  profile_name:
                    type: string
                    example: "Conservative"
                  description:
                    type: string
                    example: "A conservative risk profile."
        '404':
          description: Risk profile not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "RiskProfile not found"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Profile name is required"

    delete:
      tags:
        - Risk Profiles
      summary: Delete a risk profile by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the risk profile to delete
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Risk profile deleted successfully
        '404':
          description: Risk profile not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "RiskProfile not found"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error" 