openapi: 3.0.0
info:
  title: Settings API
  version: 1.0.0
  description: API for managing settings.
tags:
  - name: Settings
    description: Operations related to settings
paths:
  /settings:
    post:
      tags:
        - Settings
      summary: Create new settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                setting_name:
                  type: string
                  example: "Notification"
                setting_value:
                  type: string
                  example: "Enabled"
      responses:
        '201':
          description: Settings created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  setting_name:
                    type: string
                    example: "Notification"
                  setting_value:
                    type: string
                    example: "Enabled"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Setting name is required"

    get:
      tags:
        - Settings
      summary: Retrieve all settings
      responses:
        '200':
          description: A list of settings
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    setting_name:
                      type: string
                      example: "Notification"
                    setting_value:
                      type: string
                      example: "Enabled"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error"

  /settings/{id}:
    get:
      tags:
        - Settings
      summary: Retrieve a specific setting by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the setting to retrieve
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Setting found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  setting_name:
                    type: string
                    example: "Notification"
                  setting_value:
                    type: string
                    example: "Enabled"
        '404':
          description: Setting not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Settings not found"

    put:
      tags:
        - Settings
      summary: Update a setting by ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the setting to update
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                setting_name:
                  type: string
                  example: "Notification"
                setting_value:
                  type: string
                  example: "Enabled"
      responses:
        '200':
          description: Setting updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  setting_name:
                    type: string
                    example: "Notification"
                  setting_value:
                    type: string
                    example: "Enabled"
        '404':
          description: Setting not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Settings not found"
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Setting name is required"